### ISSUE TITLE
Simplify semantic versioning logics

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#100]
## Simplify `setup.py`
Now that we've got a `pyproject.toml`, we no longer need to have all the same information in `setup.py`. 

[This StackOverflow answer](https://stackoverflow.com/a/62983901/10316188) describes how the setup.py file can be replaced with a simple _shim_ that looks like this:

```py
import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

## Use `poetry-version-plugin` to get version from git tag
Using [this plugin](https://github.com/tiangolo/poetry-version-plugin#set-the-version-in-a-git-tag), we will be able to remove the hardcoded version from the entire application, and instead rely exclusively on git tags. This will make the git tag a [Single Source of Truth](https://en.wikipedia.org/wiki/Single_source_of_truth), which means we never have to manually update these hardcoded strings again. Instead we just make releases without worrying about that.

## Get rid of all the current version utils
We're currently managing the version in three different places.
- `pyproject.toml`
- `blackbox/__version__.py`
- `blackbox/utils/version.py`

The two latter files can be completely removed after we do the above refactoring.

## Fix workflows
This will break our pypi publish workflow, because it relies on the version.py uil. We can fix this by updating it to use the tag that is provided as metadata during the release API event.

**Comment by lemonsaurus** [comment]
Confirmed working

**Comment by lemonsaurus** [comment]
Actually, there appears to be a bug with this. I'll look at it now.

```
Skipping virtualenv creation, as specified in config file.
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/blackbox/blackbox/cli.py", line 22, in <module>
from blackbox.utils.version import get_project_version
ModuleNotFoundError: No module named 'blackbox.utils.version'
```

Guess I forgot to remove it from the cli.py
