### ISSUE TITLE
Blackbox crashes when no cooldown is defined.

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#95]
It appears there's a crash related to configurations that don't define a cooldown. Kinda critical.

```py
2021-06-02 16:18:38    
15:18:38 cooldown is not defined in the blackbox.yaml file -- returning an falsy value.
2021-06-02 16:18:38    
15:18:38 Cooldown period set to None
2021-06-02 16:18:38    
Traceback (most recent call last):
2021-06-02 16:18:38    
  File "/usr/local/bin/blackbox", line 33, in <module>
2021-06-02 16:18:38    
    sys.exit(load_entry_point('blackbox-cli', 'console_scripts', 'blackbox')())
2021-06-02 16:18:38    
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
2021-06-02 16:18:38    
    return self.main(*args, **kwargs)
2021-06-02 16:18:38    
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
2021-06-02 16:18:38    
    rv = self.invoke(ctx)
2021-06-02 16:18:38    
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
2021-06-02 16:18:38    
    return ctx.invoke(self.callback, **ctx.params)
2021-06-02 16:18:38    
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
2021-06-02 16:18:38    
    return callback(*args, **kwargs)
2021-06-02 16:18:38    
  File "/blackbox/blackbox/cli.py", line 167, in cli
2021-06-02 16:18:38    
    success = run()
2021-06-02 16:18:38    
  File "/blackbox/blackbox/cli.py", line 76, in run
2021-06-02 16:18:38    
    is_on_cooldown_ = is_on_cooldown(cooldown)
2021-06-02 16:18:38    
  File "/blackbox/blackbox/utils/cooldown.py", line 65, in is_on_cooldown
2021-06-02 16:18:38    
    delta = parse_config_cooldown(cooldown)
2021-06-02 16:18:38    
  File "/blackbox/blackbox/utils/cooldown.py", line 26, in parse_config_cooldown
2021-06-02 16:18:38    
    match = _DURATION_REGEX.fullmatch(cooldown)
2021-06-02 16:18:38    
TypeError: expected string or bytes-like object
```

**Comment by lemonsaurus** [comment]
Fixed in #96
